alias oldvim='/usr/bin/vim'
alias vim='nvim'
alias dots='bash ~/dotfiles/update.sh'
alias vl='source .venv/bin/activate'
# ACS Aliases
alias acs='cd ~/masters/acs/'
alias rcomp='open ~/masters/acs/mat/comp.pdf &'
alias rics='open ~/masters/acs/mat/Saltzer-Kaashoek-IntroCS.pdf &'
alias rdbms='open ~/masters/acs/mat/dbms3rd.pdf &'
alias jcrs='cd ~/masters/acs/java-course/'
